name: PDI application CI pipeline

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development-pdi
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint for project code quality
        run: |
          npm run lint:report || true

      - name: Upload Lint reports
        uses: actions/upload-artifact@v4
        with: 
          name: lint-report
          path: eslint-report.html

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Snyk Dependency Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SYNK }}
        with:
          command: test


      # used self hosted sonar qube server
      # - name: SonarQube Scan
      #   uses: SonarSource/sonarqube-scan-action@v2.0.2
      #   with:
      #     projectBaseDir: .
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}